theme: jekyll-theme-modernist
description: Synaptans WorkforceSim is a free open-source platform for simulating the dynamics of a factory workforce; employing diverse forms of machine learning to identify trends and correlations in workers’ behavior; and then comparing and assessing the accuracy of such approaches to predictive workplace analytics.
